### ISSUE TITLE
Host app on github pages

### ISSUE THREAD

**Issue by EverlastingBugstopper** [thomas-williams/who-twote-what#6]
So we can look at progress w/o checking out repo and building everything

https://github.com/gitname/react-gh-pages#procedure

**Comment by the-arkhive** [comment]
Followed the official tutorial on deploying create-react-app to GitHub Pages and it is not working for my at the moment. Might need to wait until the hello-world page is on the master branch. I tried opening the index.html file that was generated in the currently ignored build folder with live server and all it gave was a white page. For the official documentation of create-react-app and GitHub pages see the link below.

[https://facebook.github.io/create-react-app/docs/deployment#github-pages-https-pagesgithubcom](https://facebook.github.io/create-react-app/docs/deployment#github-pages-https-pagesgithubcom)
